name: stockfolio
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  flutter: '>=3.19.3'
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: 4.16.1
  country_picker: 2.0.25
  cupertino_icons: 1.0.6

  firebase_auth: 4.19.1
  firebase_core: 2.29.0
  firebase_storage: 11.7.1
  fk_toggle: 0.1.4
  fl_chart: 0.67.0
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.5

  http: 1.2.1

  image_picker: 1.0.8
  intl: 0.19.0

  lottie: 3.1.0

  pinput: 4.0.0

  shared_preferences: 2.2.3
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
